### ISSUE TITLE
Database prepopulation does not work in time

### ISSUE THREAD

**Issue by kaustika** [braille-systems/learn-braille#57]
- deleting cash and app itself doesn't help
- happens not only when you open parctice right after installation

**Comment by winter-yuki** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.spbstu.amd.learnbraille, PID: 22050
    java.lang.IllegalStateException: DB is not initialized
        at ru.spbstu.amd.learnbraille.screens.practice.PracticeViewModel$initializeCard$1.invokeSuspend(PracticeViewModel.kt:140)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
